#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FiniteAutomatonPractice2.Resource", IsApplication=true)]

namespace FiniteAutomatonPractice2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int btnConvertToDeterministic = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int btnCreate = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int btnFinish = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int btnLoad = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int btnOperations = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int btnRemoveEqualStates = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int btnRemoveStrangeStates = 2131034127;
			
			// aapt resource value: 0x7f050016
			public const int btnSaveFiniteAutomaton = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int btnSaveInputSymbols = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int btnSaveStates = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int btnSaveTransition = 2131034133;
			
			// aapt resource value: 0x7f050007
			public const int btnTransitions = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int checkIsAceptance = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int lblInputSymbols = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int lblItemTitle = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int lblStates = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int lblTransitions = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int spinnerActualState = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int spinnerDestinationState = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int spinnerInputSymbol = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int txtAutomatonType = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int txtInputSymbols = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int txtStates = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int create_automaton_activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int state_spinner_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int summary_activity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int test_automaton_activity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int transitions_activity = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
